import "/styles/globals.css";
import ContextLayout from "./context-layout";

export const metadata = {
  title: "Cambusa Ai",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextLayout>{children}</ContextLayout>
      </body>
    </html>
  );
}
